### ISSUE TITLE
Não é possível aumentar o tento em jogo de Bot contra Bot

### ISSUE THREAD

**Issue by HDK101** [lucas-ifsp/CTruco#10]
Não sei se é um bug ou uma falha na implementação do Bot, mas há momentos em que meu bot tenta aumentar a aposta, de 6 para 9, ou seja, o evento RAISE, porém a instância de Intel(utilizada no método playWithBots da classe PlayWithBotsUseCase) diz que não é possível lançar um evento RAISE uma vez que a lista de strings retornada no método possibleActions é ["QUIT", "ACCEPT"].

Seria alguma regra do Truco que não estou sabendo?

A imagem abaixo ilustra o estado da instância da classe Intel

[![image.png](https://i.postimg.cc/XY01HTzX/image.png)](https://postimg.cc/jLZhCkKr)

**Comment by lucas-ifsp** [comment]
@HDK101 Nesse caso, há uma proposta em andamento valendo nove. Estou vendo também que o jogador que tem menos ponto precisa de no máximo nove pontos. Pode ser por isso. Teste se "faz sentido" dar RAISE considerando o proposal + 3 a partir da pontuação dos jogadores.

**Comment by lucas-ifsp** [comment]
@HDK101 o bug foi resolvido, pode dar um pull que não está dando mais exception. O que estava acontecendo: o método getRaiseResponse() deve retornar -1 (quit), 0 (accept) e 1 (re-raise). Só que quando os pontos da mão chegam a um valor suficiente para que o jogador com menos pontos ganhe o jogo, só devem ser retornados valores -1 ou 0, já que RAISE não está entre as possibleActions. O método que invocava o getRaiseResponse() não tratava isso e aceitava o valor 1, encerrando o jogo. Agora, se getRaiseResponse() retornar 1 e RAISE não estiver entre as possibleActions, o jogo considera o retorno como 0 (ACCEPT) e o jogo continua. Além disso, foi colocado um tratamento de exceção para qualquer valor fora do range (-1, 1), evitando o travamento pelo mesmo motivo.
