### ISSUE TITLE
Descarte de cartas permitido na primeira rodada

### ISSUE THREAD

**Issue by Ingridnery** [lucas-ifsp/CTruco#2]
Na execução interativa no terminal, na primeira rodada do jogo  é permitido descartar a carta

**Comment by lucas-ifsp** [comment]
O bug foi resolvido. Na verdade, era mais que um bug, era uma feature não considerada no desenvolvimento. Por isso, foi necessário atualizar tanto o domínio quanto o console, o desktop e também o MineiroBot. Sugiro fazer um novo fork da versão v.1.4.1 ou atualizar a sua versão com um fetch, dessa forma: https://stackoverflow.com/questions/7244321/how-do-i-update-or-sync-a-forked-repository-on-github. @Ingridnery  obrigado por notar o problema ❤️
